
version: "3"

services:

  nginx:
    image: randomtoolguysazurecontainerregistry.azurecr.io/wasacommunity:nginx-1
    ports:
      - "81:80"
      - "443:443"

  angular:
    image: randomtoolguysazurecontainerregistry.azurecr.io/wasacommunity:angular-1
    ports:
    - "4200:80"

  dotnetcore:
    image: randomtoolguysazurecontainerregistry.azurecr.io/wasacommunity:aspnetcore-1
    depends_on:
        - database
    command: ["./wait-for-it.sh", "database:1433", "--timeout=8", "--strict", "--", "dotnet", "WasaCommunity.dll"]
    environment:
      - ConnectionString=Server=database;Database=WasaCommunityData;User Id=sa;Password=P@ssw0rd!
      - ConnectionString=Server=database;Database=WasaCommunityData.OAuth;User Id=sa;Password=P@ssw0rd!

  database:
    image: microsoft/mssql-server-linux:latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "P@ssw0rd!"
      MSSQL_PID: "Express"
    volumes:
      - demo-data:/var/lib/sqlexpress

volumes:
  demo-data: