version: "3.1"

services:

  nginx-service:
    container_name: nginx-container
    image: personal-hub:55000/wasacommunity:nginx-ci50
    volumes:
      - ./dist:/usr/share/nginx/html
    ports:
      - "81:80"
      - "443:443"

    networks:
      - app-network

  angular-service:
    container_name: angular-container
    image: personal-hub:55000/wasacommunity:angular-ci50
    ports:
    - "4200:80"
    networks:
        - app-network
    depends_on:
      - nginx-service

  dotnetcore-service:
    container_name: dotnetcore-container
    image: personal-hub:55000/wasacommunity:aspnetcore-ci50
    restart: unless-stopped
    ports:
    - "5000:5000"
    depends_on:
        - database-service
        - nginx-service
    command: ["./wait-for-it.sh", "database-service:1433", "--timeout=8", "--strict", "--", "dotnet", "WasaCommunity.dll"]
    networks:
      - app-network

  database-service:
    container_name: database-container
    image: microsoft/mssql-server-linux:latest
    networks:
        - app-network
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "P@ssw0rd!"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - data:/var/lib/sqlexpress

networks:
  app-network:
    driver: bridge

volumes:
  data:
    external: true